services:
  - type: web
    name: cerebrova
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --config gunicorn.conf.py app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: YOLO_CONFIG_DIR
        value: /tmp/.yolo_config
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
